{% set name = "garnett" %}
{% set version = "0.7.0" %}
{% set sha256 = "879343c890805b6376d6bde94614e84070d9835e739dee04b7d3fe622af10e84" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/glotzerlab/garnett/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install --install-option=\"--no-cython\" . -vv"

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools

  run:
    - deprecation >=2
    - numpy >=1.14
    - python >=3.5
    - rowan >=0.5

test:
  imports:
    - garnett

about:
  home: https://github.com/glotzerlab/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'This is a collection of samples, parsers and writers for formats used in the Glotzer Group at the University of Michigan, Ann Arbor.'
  doc_url: https://{{ name }}.readthedocs.io/
  dev_url: https://github.com/glotzerlab/{{ name }}

extra:
  recipe-maintainers:
    - lyrivera
    - klywang
    - bdice
    - joaander
