{% set name = "garnett" %}
{% set version = "0.6.1" %}
{% set sha256 = "47d4c59d2042bdb8ded415e8a5782d50777c112196070401d744df494ac3e134" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://glotzerlab.engin.umich.edu/Downloads/{{ name }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [py<35]

requirements:
  build:
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - rowan

test:
  imports:
    - garnett

about:
  home: https://github.com/glotzerlab/{{ name }}
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'This is a collection of samples, parsers and writers for formats used in the Glotzer Group at the University of Michigan, Ann Arbor.'
  doc_url: https://{{ name }}.readthedocs.io/
  dev_url: https://github.com/glotzerlab/{{ name }}

extra:
  recipe-maintainers:
    - lyrivera
    - klywang
    - bdice
    - joaander
